<a href="https://colab.research.google.com/github/imhilla/np/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# introduction to python matrices and numpy

In [6]:
# about jupyter notebooks
import numpy as np

In [5]:
one_dimentional_arr = np.array([10, 12])
print(one_dimentional_arr)

[10 12]


In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
# using arrange
b = np.arange(3)
print(b)

[0 1 2]


In [11]:
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [15]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [18]:
char_arr = np.array(['Welcome to Matrh for ML!'])
print(char_arr.dtype)

<U24


In [19]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [20]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [21]:
empty_arr = np.empty(3)
print(empty_arr)

[0. 0. 0.]


In [22]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.5087895  0.03683772 0.52288881]


In [23]:
two_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [25]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])
multi_dim_arr = np.reshape(one_dim_arr, (2, 3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [27]:
# finding shape, size, dimension
multi_dim_arr.ndim

2

In [28]:
multi_dim_arr.shape

(2, 3)

In [29]:
multi_dim_arr.size

6

In [32]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])
addition = arr_1 + arr_2
print(addition)

[ 3  7 11]


In [33]:
subtraction = arr_1 - arr_2
print(subtraction)

[1 1 1]


In [34]:
multiplication = arr_1 * arr_2
print(multiplication)

[ 2 12 30]


In [36]:
# multiplying vector with a scalar (broadcasting)
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

In [37]:
# stacking
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [38]:
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [39]:
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
